FROM node:20-alpine

# Set the working directory in the container
WORKDIR /app

COPY . /app

# Install dependencies
RUN npm install

# Build the Next.js application
RUN npm run build

# Expose the port that the application will run on
EXPOSE 3000

# Command to run the application
CMD ["npm", "run", "frontend"]